# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: NetBook API
            description: Documentation de l'API Book
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)